mqtt:
    prefix: "turrisGadgets/"
    server: "localhost"
    port: 1883
    timeout: 60
    client_id: "demo_mpd_volume_thermostat"
    default_qos: 2

    # leave empty for anonymous access
    user: 
    password: 
    
mpd:
    server: "localhost"
    port: 6600
    
    # leave empty for anonymous access
    password: 